Repository adaptlearning/adapt-contrib-resources, pull requests merged in 2025-03, with the labels that each got.

#127 Chore: Add support for new issue experience (fixes #124)
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/issue_template.md
Labels: bug

#126 New: Migration scripts added to repo (fixes #125)
  migrations/v2.js
  migrations/v3.js
  migrations/v4.js
  migrations/v5.js
Labels: enhancement, ready to release

#129 Chore: Add _isGlobal to example.json and README.md (fixes #128)
  README.md
  example.json
Labels: ready to release, documentation
